name: 'Install Roswell & Qlot'

inputs:
  qlfile-template:
    description: 'Jinja template for qlfile'
    required: false
    default: 'no temlplate'    
  lisp-system:
    description: 'ASDF system to install and test'
    required: false
    default: ''
  run-tests:
    description: A command to run tests
    required: false
    default: |
      qlot exec ros --eval '(asdf:test-system :${{ inputs.lisp-system }})' --quit

runs:
  using: composite
  steps:
    - name: Current Env
      shell: bash
      run: |
        echo ::group::Environment
        env | sort -u
        echo ::endgroup::
    - name: Install Roswell
      shell: bash
      run: |
        if [[ "$OS" == "ubuntu-latest" ]]; then
            sudo apt-get -y install git build-essential automake libcurl4-openssl-dev
        fi
        if [[ "$OS" == "macos-latest" ]]; then
            brew install automake autoconf curl
        fi
        
        curl -L https://raw.githubusercontent.com/svetlyak40wt/roswell/patches/scripts/install-for-ci.sh | sh
        
        echo $HOME/.roswell/bin >> $GITHUB_PATH
    - name: Upgrade ASDF to the Latest Version
      shell: bash
      run: |
        ros install asdf
    - name: Install Qlot
      shell: bash
      run: |
        ros install qlot
        echo .qlot/bin >> $GITHUB_PATH

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ -e qlfile ]]; then
          rm -fr qlfile.lock
        else:
          if [[ "${QUICKLISP_DIST}" == 'ultralisp' ]]; then
            echo dist ultralisp http://dist.ultralisp.org/ >> qlfile
          fi
        fi
        qlot install
      - name: Install System
        run: |
          if [[ "${QUICKLISP_DIST}" == 'quicklisp' ]]; then
              qlot exec ros install 40ants/defmain
          fi

          qlot exec ros install cl-info
      - name: Install System
        run: |
          if [[ "${QUICKLISP_DIST}" == 'quicklisp' ]]; then
              qlot exec ros install 40ants/defmain
          fi

          qlot exec ros install cl-info
