name: 'Build Docs'

inputs:
  asdf-system:
    description: 'ASDF system to build system for'
    required: true
  qlfile-template:
    description: "Djula template for qlfile. All environment variables are available in it's context"
    required: false

runs:
  using: composite
  steps:
    - name: Install Documentation Builder
      shell: bash
      run: |
        echo ::group::Install Documentation Builder

        echo 'github docs-builder 40ants/docs-builder' >> qlfile
        
        qlot update

        qlot exec ros install docs-builder
        echo ::endgroup::

    - name: Build Docs
      id: build-docs
      shell: bash
      run: |
        OUTPUT_DIR=$(build-docs ${{ inputs.asdf-system }})
        
        echo "::set-output name=build-dir::${OUTPUT_DIR}"

    - name: Upload Docs
      shell: bash
      run: |
        BUILD_DIR=${{ steps.build-docs.outputs.build-dir }}

        ${{ github.action_path }}/upload.ros "${BUILD_DIR}"
