name: 'Build Docs'

inputs:
  asdf-system:
    description: 'ASDF system to build system for'
    required: true
  qlfile-template:
    description: "Djula template for qlfile. All environment variables are available in it's context"
    required: false

runs:
  using: composite
  steps:
    - name: Install Documentation Builder
      shell: bash
      run: |
        echo ::group::Install Documentation Builder

        echo 'github docs-builder 40ants/docs-builder' >> qlfile
        
        qlot update

        qlot exec ros install docs-builder
        echo ::endgroup::

    - name: Build Docs
      shell: bash
      run: |
        set -x
        ls .qlot
        ls .qlot/bin
        echo $PATH
        cat qlfile
    
        build-docs ${{ inputs.asdf-system }}
