name: 'Docs'

on:
  # This will run tests on pushes
  # to master branch or on pull merges:
  push:
    branches:
      - 'main'
      - 'master'
  # This will run tests for every pull request:
  pull_request:
  # Rerun tests at 10 AM every Monday
  # to check if they still work with latest dependencies.
  schedule:
    - cron:  '0 10 * * 1'

jobs:
  build-docs:
    runs-on: ubuntu-latest
    
    env:
      LISP: sbcl-bin

    steps:
      - uses: actions/checkout@v1
      - uses: 40ants/cl-info/.github/actions/setup-lisp@custom-action
        with:
          asdf-system: cl-info
          qlfile-template: |
            github mgl-pax svetlyak40wt/mgl-pax :branch mgl-pax-minimal
      
      - uses: 40ants/cl-info/.github/actions/build-docs@custom-action
        with:
          asdf-system: cl-info
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #     NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #     NGROK_REGION: eu
      #     SSH_PASS: ${{ secrets.SSH_PASS }}

