name: 'Check Installation'

on:
  # This will run tests on pushes
  # to master branch or on pull merges:
  push:
    branches:
      - 'main'
      - 'master'
  # This will run tests for every pull request:
  pull_request:
  # Rerun tests at 10 AM every Monday
  # to check if they still work with latest dependencies.
  schedule:
    - cron:  '0 10 * * 1'

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        lisp:
          - sbcl-bin
          - ccl-bin
        os:
          - ubuntu-latest
          - macos-latest
          
    runs-on: ${{ matrix.os }}
    
    env:
      LISP: ${{ matrix.lisp }}
      OS: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Show env
        run: |
          env | sort -u
      - name: Install Roswell
        run: |
          curl -L https://raw.githubusercontent.com/svetlyak40wt/roswell/patches/scripts/install-for-ci.sh | sh
          echo $HOME/.roswell/bin >> $GITHUB_PATH
      - name: Upgrade ASDF to the latest version
        run: |
          ros install asdf
      - name: Install Qlot
        run: |
          ros install qlot
          echo .qlot/bin >> $GITHUB_PATH
      - name: Install Dependencies
        run: |
          rm -fr qlfile
          echo dist ultralisp http://dist.ultralisp.org/ >> qlfile

          qlot install
      - name: Install CL-INFO
        run: |
          qlot exec ros install 40ants/cl-info
      - name: Run CL-INFO
        run: |
          qlot exec cl-info

