name: 'Check Installation'

on:
  # This will run tests on pushes
  # to master branch or on pull merges:
  push:
    branches:
      - 'main'
      - 'master'
  # This will run tests for every pull request:
  pull_request:
  # Rerun tests at 10 AM every Monday
  # to check if they still work with latest dependencies.
  schedule:
    - cron:  '0 10 * * 1'

jobs:
  run_tests:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        quicklisp-dist:
          - quicklisp
          # - ultralisp
        lisp:
          - sbcl-bin
          - ccl-bin
          # - ecl
          # - abcl
          # - allegro
          # - clisp
          # - cmucl
        # include:
        #   # Seems allegro is does not support 64bit OSX.
        #   # Unable to install it using Roswell:
        #   # alisp is not executable. Missing 32bit glibc?
        #   - lisp: allegro
        #     os: macos-latest
        #     can-fail: true
        #   # CLisp on Ubuntu can't be installed because of the error:
        #   # #<FOREIGN-VARIABLE "rl_readline_state" #x00007FA93E698850> does not have
        #   # the required size or alignment
        #   - lisp: clisp
        #     os: ubuntu-latest
        #     can-fail: true
        #   # CMUCL is 32bit and cant' work on 64bit OSX:
        #   # .roswell/impls/x86-64/darwin/cmu-bin/21d/bin/lisp is not executable. Missing 32bit glibc?
        #   - lisp: cmucl
        #     os: macos-latest
        #     can-fail: true
          

    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.can-fail || false }}
    
    env:
      LISP: ${{ matrix.lisp }}
      OS: ${{ matrix.os }}
      QUICKLISP_DIST: ${{ matrix.quicklisp-dist }}

    steps:
      - uses: actions/checkout@v1
      - uses: 40ants/cl-info/.github/actions/setup@custom-action
        with:
          - custom-code: |
              (progn
                (ros:ensure-asdf)
                #+quicklisp
                (ql:quickload '() :silent t))
      
              (defun main (args)
                 (declare (ignore args))
                 (format t "::group::Custom Roswell Script~%")
                 (format t "Lisp: ~A ~A~%ASDF: ~A~%"
                         (lisp-implementation-version)
                         (lisp-implementation-type)
                         (asdf:asdf-version))
                 (format t "::endgroup::~%"))
        
      # - name: Start SSH session
      #   uses: luchihoratiu/debug-via-ssh@main
      #   with:
      #       NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
      #       NGROK_REGION: eu
      #       SSH_PASS: ${{ secrets.SSH_PASS }}

      # - name: Install System
      #   run: |
      #     if [[ "${QUICKLISP_DIST}" == 'quicklisp' ]]; then
      #         qlot exec ros install 40ants/defmain
      #     fi

      #     qlot exec ros install cl-info
      # - name: Run Tests
      #   run: |
      #     set -x
      #     qlot exec cl-info --help
      #     qlot exec cl-info --version
      #     qlot exec cl-info cl-info
